on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: [self-hosted,Linux,X64,trustcrews240603this]
    environment: dev
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3

      - name: Cache dependencies
        id: cache-deps
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: |
            '**/package.json'
            '**/package-lock.json'

      - name: Install Dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: npm ci --legacy-peer-deps

      - run: npm run build --if-present
      - run: pm2 restart "trustcrews-front"
