
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: [self-hosted,Linux,X64,trustcrews240603this]
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      
      - name: Cache Node modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - run: npm ci --legacy-peer-deps

      - run: npm run build --if-present

      - run: pm2 restart "trustcrews-front"
