on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: [self-hosted,Linux,X64,trustcrews240603this]
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v3
        id: cache-deps
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: npm ci --legacy-peer-deps

      - name: Build
        run: npm run build --if-present

      - run: pm2 restart "trustcrews-front"
